### ISSUE TITLE
Broken Jar

### ISSUE THREAD

**Issue by henry-lp** [SpoonLabs/sonarqube-repair#94]
The `jar-with-dependencies` does not work anymore. 

Bug reproduction steps:
```
git clone git@github.com:SpoonLabs/sonarqube-repair.git
cd sonarqube-repair
./init.sh
mvn package -DskipTests
java -jar target/sonarqube-repair-1.1-SNAPSHOT-jar-with-dependencies.jar --originalFilesPath src/test/resources/ --rulesKey 2116
```

Error output:
```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Exception in thread "main" java.lang.ExceptionInInitializerError
	at sonarquberepair.DefaultRepair.repair(DefaultRepair.java:33)
	at sonarquberepair.Main.start(Main.java:84)
	at sonarquberepair.Main.main(Main.java:90)
Caused by: java.lang.UnsupportedOperationException: No class provided, and an appropriate one cannot be found.
	at org.apache.logging.log4j.LogManager.callerClass(LogManager.java:576)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:601)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:588)
	at spoon.Launcher.<clinit>(Launcher.java:589)
	... 3 more
```

On first sight it could very possibly be a dependency collision between `LogManager` of `sonarjava` and `spoon-core`  by checking line `at spoon.Launcher.<clinit>(Launcher.java:589)` . Since `spoon-core` use log4j , its [LogManager](https://logging.apache.org/log4j/2.x/log4j-api/apidocs/org/apache/logging/log4j/LogManager.html) can use the method `LogManager.getLogger()` without any arguments, while `sonarjava` use slf4j , its [LogManager](http://www.slf4j.org/api/org/apache/log4j/LogManager.html) need at least 1 argument causing the error above.

WDYT ? @fermadeiral , @monperrus  :)

**Comment by fermadeiral** [comment]
I think that what you said makes sense. It's weird that we have no issue running the program without the jar tough.

Did you think in some workaround, @henry-lp?

**Comment by henry-lp** [comment]
@fermadeiral I am working on it :) . Currently , I am trying to find out by tracing back the commit where this starts to happens. Currently it's quite foreboding indications about there something happened in just `spoon-core` unrelated to our changes to `sonarjava`. 

PS: spoon also seems to fail their CI currently.

**Comment by fermadeiral** [comment]
> I am working on it

Ok, send me news when you have.

**Comment by henry-lp** [comment]
yes :) , this does not work when I use this as a dependency for Repairnator, which traced back to this.

**Comment by henry-lp** [comment]
@fermadeiral I found the issue. It's due to my system update the my java version was switched to `java 11` caused this mess. This issue can be closed :) .

**Comment by fermadeiral** [comment]
@henry-lp are you sure? Because I had tried to reproduce the problem and I got the same output as you.

**Comment by henry-lp** [comment]
@fermadeiral I was happy too early :D . There is still more bugs apparently.

**Comment by henry-lp** [comment]
Here's the new error output:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sonarquberepair.DefaultRepair.repair(DefaultRepair.java:51)
	at sonarquberepair.Main.start(Main.java:84)
	at sonarquberepair.Main.main(Main.java:90)
Caused by: java.lang.NoClassDefFoundError: org/sonar/java/checks/CastArithmeticOperandCheck
	at sonarquberepair.processor.CastArithmeticOperandProcessor.<init>(CastArithmeticOperandProcessor.java:19)
	... 7 more
Caused by: java.lang.ClassNotFoundException: org.sonar.java.checks.CastArithmeticOperandCheck
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 8 more

```

**Comment by fermadeiral** [comment]
> Commands after packaging the JAR file

How did you do it? It seems that your error is related to not finding sonar java in the jar.

**Comment by henry-lp** [comment]
I am currently looking into this. 

One question: when you deploy `sonarqube-repair` , it's like the usual just `mvn deploy` , which in this case also include the custom sonarjava after `./init.sh`?

**Comment by fermadeiral** [comment]
> when you deploy sonarqube-repair , it's like the usual just mvn deploy , which in this case also include the custom sonarjava after ./init.sh?

Yes.

**Comment by henry-lp** [comment]
I see then the issue is not entirely unrelated to sonarjava. We might need to deploy the custom sonarjava, because now I managed to get it working fine just running the jar after building from sonarqube repair repo, but when I include it as a dependency it can't find the class path of `CastArithmeticOperandCheck` as you have seen in the output log above . :) 

WDYT ?

**Comment by fermadeiral** [comment]
> WDYT ?

I think it would be nice to have a meeting tomorrow so that we can figure it out together. This is the top priority in the project now.
