### ISSUE TITLE
rule 2095 not working

### ISSUE THREAD

**Issue by kiran-chinnapa** [SpoonLabs/sonarqube-repair#98]
I tried using the release 1.0 version of the jar, when i test against rule 2095 i am getting below error.

C:\softwares\sonar-qube-repair>java -jar sonarqube-repair-1.0-jar-with-dependencies.jar 2095
Applying sonarquberepair.processor.sonarbased.UnclosedResourcesProcessor...
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

Sending GET request to SonarQube API : https://sonarcloud.io/api/issues/search?resolved=false&ps=500&rules=squid:S2095&componentKeys=
Response Code : 400
java.lang.Exception: ERROR : Wrong Reponse Code from Sonarqube API. Check Internet Connection
        at sonarquberepair.processor.sonarbased.SonarWebAPIBasedProcessor.parse(SonarWebAPIBasedProcessor.java:66)
        at sonarquberepair.processor.sonarbased.SonarWebAPIBasedProcessor.<init>(SonarWebAPIBasedProcessor.java:23)
        at sonarquberepair.processor.sonarbased.UnclosedResourcesProcessor.<init>(UnclosedResourcesProcessor.java:19)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at sonarquberepair.Main.repair(Main.java:32)
        at sonarquberepair.Main.main(Main.java:62)
Exception in thread "main" java.lang.NullPointerException
      
Could you please check ?

**Comment by fermadeiral** [comment]
Hi @kiran-chinnapa,

> Could you please check ?

Yes!

**Comment by fermadeiral** [comment]
@kiran-chinnapa, the project you want to analyze is in sonarcloud.io? If it's not, unfortunately it's not possible to run the release 1.0 with rule 2095.

However, we are currently working on some design decisions and soon we will have a working snapshot jar file that you can use for rule 2095 without the need of sonarcloud.io.

**Comment by kiran-chinnapa** [comment]
Thank you ,how can i move my project on sonarcloud.io. Could you please provide me the steps.

**Comment by kiran-chinnapa** [comment]
Also could you please let me know which rules i can run outside the cloud ?

**Comment by fermadeiral** [comment]
> Also could you please let me know which rules i can run outside the cloud ?

2111, 2116, 2272, 4973

**Comment by kiran-chinnapa** [comment]
Thanks a lot

**Comment by fermadeiral** [comment]
@kiran-chinnapa, as I mentioned before, with the release 1.0, you need to have your project in sonarcloud.io so that sonarqube-repair works on rule 2095.

Note that this is note the case anymore in the current state of our project, so you should use our 1.1-SNAPSHOT jar file: https://oss.sonatype.org/content/repositories/snapshots/se/kth/castor/sonarqube-repair/

I'm closing this issue now, because rule 2095 is working.
